steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/flowise-dev-pipeline/flowise:dev', '.'
    ]

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/flowise-dev-pipeline/flowise:dev'
    ]

  # Step 3: Deploy the Docker image to Google Kubernetes Engine (GKE)
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/flowise'
    - 'flowise=gcr.io/flowise-dev-pipeline/flowise:dev'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'  # Set your zone here
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-flowise-october-2024'  # Set your GKE cluster name here

  # Step 4: Restart the deployment to ensure the new image is used
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'rollout'
    - 'restart'
    - 'deployment/flowise'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'  # Set your zone here
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-flowise-october-2024'  # Set your GKE cluster name here

# Cloud Build options to enable Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY  # Send logs only to Cloud Logging

# Good luck charm :)
