name: Sync Flowise Fork

on:
  schedule:
    - cron: '00 22 * * *' # Runs daily at 22:00 UTC (midnight Croatia time UTC+2)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: COGNAL-AI/Flowise
          token: ${{ secrets.GH_TOKEN }}  # Use the secret token correctly here

      - name: Set Up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/FlowiseAI/Flowise.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit

      - name: Push to Fork
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure this is passed as an environment variable
